### ISSUE TITLE
ebookmaker CRITICAL error

### ISSUE THREAD

**Issue by eshellman** [gutenbergbooks/72651#1]
https://github.com/gutenbergbooks/72651/blob/e8aa0e57d46f58c84e164d1b8f5974d6d31a5b40/72651-h/72651-h.htm#L101

2024-01-09 09:00:44,362 CRITICAL  #72651 Failed for embedded media in file:///public/vhost/g/gutenberg/html/files/72651/72651-h/72651-h.htm from disallowed location: file:///nordsec-bNX2kPHFeuujrAsW/stylesheet?id=vVySQ9DbPg2WOj1A

**Comment by nfenwick** [comment]
Do the whitewashers get these notifications? I hope so. No way that should have made it through. It also looks like the uploader's attached .info.txt file doesn't match the ebookmaker run with the .htm file that was in the project.

Do the whitewashers get these notifications or do I need to get the message to them?

**Comment by eshellman** [comment]
notifications of CRITICAL errors are sent to the contact address in the json file; hard to tell if they are received! For this one, the ww contact is Chuck G.

**Comment by eshellman** [comment]
In general, the rate of un-fixed errors has gone way down!! I hope it's because the WWers are more aware of the error notifications or some other workflow change. Nonetheless, #72651 remains CRITICAL per the monthly rebuild.

Perhaps the github channel would be a useful fallback for the (now rare) unfixed submissions.

**Comment by nfenwick** [comment]
[from Roger]: I repaired #72651 as posted and in the repository.
